### ISSUE TITLE
Announcements for a regatta

### ISSUE THREAD

**Issue by jbfraser1** [SailScores/SailScores#55]
At a regatta, official announcements usually exist in a physical place. How can Sailscores support sharing of the official announcements? In particular timing of next races seems helpful to sailors that might be checking scores.

**Comment by jbfraser1** [comment]
One suggestion (thanks Ryan) was to allow for upload of pics of the official notice board. Would have to figure out how to moderate this.

**Comment by natrad100** [comment]
You could extend the 'club' page to have a post setup for notifications. Simply make a model that includes a title, subtitle and content and allow for creation of those models back end. Have it display the most recent 2/3 on the club page, then have a more button to see more.

Could potentially have it linked specifically with regattas?

**Comment by jbfraser1** [comment]
That makes sense: The posts could be connected to various things, like series or regattas.
I wonder if two different options could work together:
1. Allow authorized users to post and skip approval.
2. Anonymous users can post, but the post goes to a "Waiting for approval" list for an authorized user to check before accepting.
I'd really like some way for everyone at a regatta to be able to contribute, without needing to create an account, but maybe that's not a big deal?

**Comment by jbfraser1** [comment]
working on this in the next few weeks. Planning on using summernote wysiwyg editor, keeping a list of announcements for a regatta, and they'll have a few attributes to preserve history and how long they should be displayed for on the regatta's page.

**Comment by jbfraser1** [comment]
Most work on this is complete. Still testing.
